require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/forecasts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Forecast. As you add validations to Forecast, be sure to
  # adjust the attributes here as well.
  
  let(:address) { '620 Herndon Parkway, Herndon, VA 20170-4826' }
  let(:postal_code) { '94043' }
  let(:cache_key) { "forecast_zip:#{postal_code}" }
  let(:geocode_result) { OpenStruct.new(latitude: 38.969, longitude: -77.385) }

  let(:provider_double) { instance_double(WeatherProvider::OpenWeatherAdapter) }

  before do
    ## Clear cache and stub AddressParser & Geocoder
    Rails.cache.clear

    parser = instance_double(AddressParser)
    allow(AddressParser).to receive(:new).with(address).and_return(parser)
    allow(parser).to receive(:postal_code!).and_return(postal_code)

    allow(Geocoder).to receive(:search).with(address).and_return([geocode_result])
  end

  describe 'GET' do
    it 'renders the lookup form' do
      get '/'
      expect(response).to have_http_status(:ok)
      expect(response.body).to include('Address')
      expect(response.body).to include('Get')
    end
  end

  describe 'GET /forecast' do
    context 'when address param is missing' do
      it 'returns a bad request for JSON' do
        get '/forecast', headers: { 'ACCEPT' => 'application/json' }
        expect(response).to have_http_status(:bad_request)
        body = JSON.parse(response.body)
        expect(body['error']).to be_present
      end

      it 'redirects to root with alert for HTML' do
        get '/forecast'
        # Our controller redirects to root_path when address missing
        expect(response).to redirect_to(root_path)
      end
    end

    context 'when cached data exists' do
      it 'returns cached: true in JSON response' do
        cached_payload = {
          temperature_c: 12.3,
          temperature_f: 54.14,
          high_c: 14.0,
          low_c: 8.0,
          description: 'partly cloudy',
          fetched_at: Time.current.iso8601,
          provider: 'open_weather',
          postal_code: postal_code,
          cached: true
        }
        Rails.cache.write(cache_key, cached_payload, expires_in: 30.minutes)

        get '/forecast', params: { address: address }, headers: { 'ACCEPT' => 'application/json' }

        expect(response).to have_http_status(:ok)
        body = JSON.parse(response.body)
        expect(body['cached']).to eq(true)
        expect(body['postal_code']).to eq(postal_code)
        expect(body['temperature_c']).to eq(12.3)
      end
    end

    context 'when cache data miss and provider returns data' do
      before do
        allow(WeatherProvider::OpenWeatherAdapter).to receive(:new).and_return(provider_double)
      end

      it 'renders HTML show page with fresh result' do
        allow(provider_double).to receive(:current_forecast_for).and_return({
          temperature_c: 20.0,
          temperature_f: 68.0,
          high_c: 22.0,
          low_c: 15.0,
          description: 'sunny',
          fetched_at: Time.current.iso8601,
          provider: 'open_weather'
        })

        get '/forecast', params: { address: address }
        expect(response).to have_http_status(:ok)
        expect(response.body).to include('Forecast for')
        expect(response.body).to match(/Temperature:/)
        expect(response.body).to include('Fresh result').or include('Result from cache')
      end
    end
  end

end
